
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
/*

export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS';
export const ADD_EMPLOYEE_FAILURE = 'ADD_EMPLOYEE_FAILURE';

export const GET_EMPLOYEES_SUCCESS='GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_FAILURE='GET_EMPLOYEES_FAILURE';
*/

export const GET_EMPLOYEES_SUCCESS='GET_EMPLOYEES_SUCCESS';



